.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH XMLRPC-C 7 "June 26, 2001"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
xmlrpc-c \- Library for making RPC calls over HTTP using XML
.SH DESCRIPTION
\fBxmlrpc-c\fP is a library which allows C and C++ programs to make
RPC calls over HTTP using specially-formatted XML messages.

This man page contains pointers to the real documentation for
xmlrpc-c (which is only semi-adequate, but that's another problem).

.SH SEE ALSO
.BR http://xmlrpc-c.sourceforge.net/ ,
.BR http://www.xml-rpc.com/ ,
.BR /usr/share/doc/xmlrpc-c*/ ,
.BR /usr/include/xmlrpc*.h ,
.BR xmlrpc-c-config (1),
.BR xml-rpc-api2txt (1),
.BR xml-rpc-api2cpp (1),
.BR meerkat-app-list (1),
.BR query-meerkat (1).

.SH AUTHOR
This manual page was written Eric Kidd <eric.kidd@pobox.com>.
It may be distributed under the same terms as the rest of xmlrpc-c.
