#! /bin/sh

#==============================================================================
# This program generates include file <xmlrpc-c/config.h>.
#
# That's a file that gets installed on the user's system along with the other
# Xmlrpc-c interface header files.  It contains declarations of the installed
# environment.  The other header files include <xmlrpc-c/config.h>.  Note that
# this file is part of the compile of _user_ programs that use Xmlrpc-c, so is
# different from the environment-declaring files you see that are used in
# building Xmlrpc-c itself.
#
# We build a temporary file and rename it after it is complete, so that
# Make will never see a partially built file, assume the dependency on
# config.h is met, and do some compile that uses config.h.
#
# We expect to run with the 'include' subdirectory of the build tree
# as our current directory.
#==============================================================================

target_filename=$1
HAVE_WCHAR_H_DEFINE=$2

t=$target_filename.temp

echo '#ifndef XMLRPC_C_CONFIG_H_INCLUDED'                        >>$t
echo '#define XMLRPC_C_CONFIG_H_INCLUDED'                        >>$t
echo ''                                                          >>$t
echo '/* This file, part of XML-RPC For C/C++, is meant to '     >>$t
echo '   define characteristics of this particular installation '>>$t 
echo '   that the other <xmlrpc-c/...> header files need in '    >>$t
echo '   order to compile correctly when #included in Xmlrpc-c'  >>$t
echo '   user code.'                                             >>$t
echo ''                                                          >>$t
echo '   Those header files #include this one.'                  >>$t
echo ''                                                          >>$t
echo '   This file was created by a make rule.'                  >>$t
echo '*/'                                                        >>$t
echo "#define XMLRPC_HAVE_WCHAR $HAVE_WCHAR_H_DEFINE"            >>$t
echo '#ifdef WIN32'                                              >>$t
echo '  /* SOCKET is a type defined by <winsock.h>.  Anyone who' >>$t
echo '     uses XMLRPC_SOCKET on a WIN32 system must #include'   >>$t
echo '     <winsock.h>'                                          >>$t
echo '  */'                                                      >>$t
echo '  #define XMLRPC_SOCKET SOCKET'                            >>$t
echo '  #define XMLRPC_HAVE_TIMEVAL 0'                           >>$t
echo '  #define XMLRPC_HAVE_TIMESPEC 0'                          >>$t
echo '#else'                                                     >>$t
echo '  #define XMLRPC_SOCKET int'                               >>$t
echo '  #define XMLRPC_HAVE_TIMEVAL 1'                           >>$t
echo '  #define XMLRPC_HAVE_TIMESPEC 1'                          >>$t
echo '#endif'                                                    >>$t
echo ''                                                          >>$t
echo '#if defined(_MSC_VER)'                                     >>$t
echo '  /* Newer MSVC has long long, but MSVC 6 does not */'     >>$t
echo '  #define XMLRPC_INT64 __int64'                            >>$t
echo '  #define XMLRPC_INT32 __int32'                            >>$t
echo '#else'                                                     >>$t
echo '  #define XMLRPC_INT64 long long'                          >>$t
echo '  #define XMLRPC_INT32 int'                                >>$t
echo '#endif'                                                    >>$t
echo '#endif'                                                    >>$t

mv $t $target_filename

