@REM Windows build
@REM This must be RUN once to establish some header files,
@REM that are generated by the automake process
@echo creating Win32 header files...once only
@set TEMP1=
@if EXIST ..\include\xmlrpc-c\config.h goto DN1
copy .\win32_config.h ..\include\xmlrpc-c\config.h > nul
@set TEMP1=%TEMP1% ..\include\xmlrpc-c\config.h
:DN1
@if EXIST ..\xmlrpc_config.h goto DN2
copy .\xmlrpc_win32_config.h ..\xmlrpc_config.h > nul
@set TEMP1=%TEMP1% ..\xmlrpc_config.h
:DN2
@if EXIST ..\transport_config.h goto DN3
copy .\transport_config_win32.h ..\transport_config.h > nul
@set TEMP1=%TEMP1% ..\transport_config.h
:DN3
@call mkvers > nul
@if "%TEMP1%." == "." goto ALLDN
@echo Generated the following win32 header files ...
@echo %TEMP1%
@goto END

:ALLDN
@echo Using previous copies ...
@goto END

:END
