.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH XMLRPC-C-CONFIG 1 "June 27, 2001"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
xmlrpc-c-config \- Compilation helper for xmlrpc-c programs
.SH SYNOPSIS
.B xmlrpc-c-config --help
.br
.B xmlrpc-c-config
\fImodules\fR... \fIflag\fR
.SH DESCRIPTION
xmlrpc-c-config keeps track of all the flags and command-line
arguments needed to compile programs using the xmlrpc-c library.
.SH OPTIONS
.TP
.B \-\-help
Print out all legal modules and flags.
.TP
.I modules
The names of one or more modules need by the current program.
.TP
.I flag
A flag specifing whether to output preprocessor flags, linking
directives, or some other type of information.
.SH BUGS
None known.
.SH SEE ALSO
.BR xmlrpc-c (7).
.PP
This program is part of xmlrpc-c.
.SH AUTHOR
This manual page was written by Eric Kidd <eric.kidd@pobox.com>.
It may be distributed under the same terms as the rest of xmlrpc-c.
